ENV HOSTNAME=localhost
ENV EUREKA_URL=http://localhost:9150/eureka/

ENTRYPOINT ["java", "-DEUREKA_INSTANCE_HOSTNAME=${HOSTNAME}","-DEUREKA_CLIENT_SERVICEURL_DEFAULTZONE=${EUREKA_URL}", "-jar", "app.jar"]